### ISSUE TITLE
Problems with bson ??

### ISSUE THREAD

**Issue by mfa** [wilsaj/flask-admin-old#15]
I installed bson 0.3.3 via pip.
Is that not the version you are using? Please add the correct version to setup.py. 

```
from bson.errors import InvalidId

ImportError: No module named errors
```

**Comment by wilsaj** [comment]
Thanks for catching and reporting this.

The bson module in question is part pymongo, which is a dependency of MongoAlchemy - it's an artifact of the new MongoAlchemy datastore stuff. I was having datastore module automatically import both the SQLAlchemy and MongoAlchemy datastores with the idea that a shorter import path is better, but requiring MongoAlchemy for non-MongoAlchemy users is pretty dumb and same for MongoAlchemy users who shouldn't need to install SQLAlchemy. I guess there could be some try/except business in the datastore's `__init.py__` that could pull it off but I don't think it's worth the hassle.

Anyway, we avoid this at the cost of slightly longer imports for datastores and I can live with that. Thanks again!
