### ISSUE TITLE
No module named flask.ext.admin.datastore

### ISSUE THREAD

**Issue by jiangzhx** [wilsaj/flask-admin-old#26]
from flask.ext import admin
from flask.ext.admin.datastore.sqlalchemy import SQLAlchemyDatastore
from flask.ext.sqlalchemy import SQLAlchemy

i already install flask_admin.

**Comment by wilsaj** [comment]
I'm having trouble reproducing this. Can you give me some more info on what's going on?

Are you using the version from this repo or the version on pypi? Also, system stuff would be helpful: OS, python version, flask version

**Comment by wilsaj** [comment]
A little more digging and I think I found it. Can you try to pull commit 86d3bc8bb5 from the import-hook-fix branch and see if that works?

**Comment by wilsaj** [comment]
I'm going to assume that worked.
