### ISSUE TITLE
make html in doc failed

### ISSUE THREAD

**Issue by delai** [wilsaj/flask-admin-old#34]
> > make html
> > sphinx-build -b html -d _build/doctrees   . _build/html
> > Running Sphinx v1.1.3
> > loading pickled environment... done

Theme error:
no theme named 'flask_small' found (missing theme.conf?)
make: **\* [html] Error 1

**Comment by wilsaj** [comment]
This is a general flask extension thing. You have to grab the flask themes by running these in the base directory of the repo:

```
git submodule init
git submodule update
```
