### ISSUE TITLE
refactor to support other datastores

### ISSUE THREAD

**Issue by wilsaj** [wilsaj/flask-admin-old#7]
The current code is directly tied to SQLAlchemy in a lot of places. One approach that should work well is to abstract out the stuff that Flask-Admin needs to ask of a datastore into some API that can be satisfied by a datastore object of some sort; then for any datastore, we just write objects that satisfy this API and we should be good.

**Comment by charlieevett** [comment]
This is a critical feature for us, since we're using Flask-MongoAlchemy.

**Comment by wilsaj** [comment]
The major refactoring has been done and merged into master, so I'm closing this issue.

I'll add a new issue that specifically targets support for MongoAlchemy, but all we need to do at this point write a mongoalchemy datastore class similar to the one for sqlalchemy. I haven't yet experienced MongoAlchemy and I'm having difficulty getting the Flask-MongoAlchemy examples/tests to work so if someone more familiar with this stuff wants to help out or take a stab at it, it will probably get done a bit faster.
